version: '3.2'

services:

  emsa_blueocean:
    image: 'jenkinsci/blueocean'
    user: root
    volumes:
      - type: bind
        source: '/var/run/docker.sock'
        target: '/var/run/docker.sock'
      - type: bind
        source: 'C:\Users\emuser'
        target: '/home'
      - type: bind
        source: 'jenkins-data'
        target: '/var/jenkins_home'
    ports:
      - '8080:8080'

  emsa_sonarqube: 
    image: sonarqube
    ports: 
      - '9000:9000'

  # emsa_maven:
  #   image: 'maven:3-alpine'
  #   command: bash -c "while true; do echo hello; sleep 2; done"
  #   volumes:
  #     - type: bind
  #       source: '/root/.m2'
  #       target: '/root/.m2'
    